version: "2"
services:
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - /www/public
    volumes_from:
      - web
    links:
      - web:web
  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    depends_on:
      - cassandra
    volumes:
      - ./:/app
    ports:
      - "32768:3000"
    environment:
      NODE_ENV: development
      MONGODB_URL: mongodb://mongo:27017
      REDIS_PORT: 6379
      PORT: 3000
    links:
      - cassandra
  cassandra:
    build:
      context: .
      dockerfile: ./dockerfile.cassandra.yaml
    ports:
      - 7000:7000
#    command: cqlsh CREATE KEYSPACE leonardo WITH REPLICATION = { 'class' : 'SimpleStrategy', 'datacenter1' : 1 };
