version: "2"
services:
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - /www/public
    volumes_from:
      - web
    links:
      - web:web
  web:
    build:
      context: .
      dockerfile: ./app/dockerfile
    volumes:
      - ./:/app
    ports:
      - "32768:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
